### ISSUE TITLE
图片旋转问题

### ISSUE THREAD

**Issue by 0xe69e97** [Banlangenn/vue-crop#4]
图片如果是横着的，例如 IOS 下，竖着拿手机，拍出来的照片在预览的时候是横着的，旋转一下后，生成图片时，出来的图片上面和下面都被自动裁掉了一点

**Comment by Banlangenn** [comment]
这是因为，他旋转中心是图片的中心，长度大于编辑高度，就会跑到屏幕外边去了
***
解决办法 ：缩放功能  =>  双指捏合，缩小图片就好了（文档确实有些简陋了=>待我补充一下）

画布中的图片是支持 单指拖动的，双指缩放的 （画笔激活状态下手势会被禁掉）
***顺便升级一下最新版本1.0.15***

**Comment by 0xe69e97** [comment]
但是看起来并不是这样哦

在旋转的时候旋转的是 canvas 画布，并不是图片旋转

在旋转后，我看图片的实例的宽高还是旋转之前的宽高

而且这个应该是在初始化的时候，参数 `shape` 传入 `imgage` 应该是图片默认的宽高

所以在生成图片的时候

如果你旋转了

图片元素之前的高度变成了旋转后的宽度

图片元素之前的宽度变成了旋转后的高度

**Comment by 0xe69e97** [comment]
在没有开启`shape`的时候

```
shape="imgage"
```

就算放大或者缩小，图片生成的时候，还是会保持原来的尺寸的，并不会把图片显示完整

**Comment by 0xe69e97** [comment]
通过更改源码解决问题了。

**Comment by Banlangenn** [comment]
欢迎pr修改

**Comment by 0xe69e97** [comment]
好的

**Comment by Banlangenn** [comment]
http://www.wwwwxy.top/html/blg/


改了一下代码~~你看看演示链接~
